# allow bigger files
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
# Spring Boot server
server.port=8080

# JODConverter configuration
jodconverter.local.enabled=true
jodconverter.local.office-home=/Applications/LibreOffice.app/Contents

jodconverter.local.port-numbers=2002
